# Generated by Django 4.2.1 on 2023-05-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vechile_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_employee',
        ),
        migrations.AddField(
            model_name='user',
            name='is_adim',
            field=models.BooleanField(default=False, verbose_name='Is adim'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuse',
            field=models.BooleanField(default=False, verbose_name='Is superuse'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_use',
            field=models.BooleanField(default=False, verbose_name='Is use'),
        ),
    ]
